function [Y, gof] = LinearInterpolation(x1, x2)
%CREATEFIT1(X1,X2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x1
%      Y Output: x2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Oct-2024 10:59:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x1, x2 );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'x2 vs. x1', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel x1
% ylabel x2
% grid on
xt=x1(1):x1(end);
Y=fitresult(xt);
end



